apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: lh7a27vzf-go 
  janus-idp.io/tekton: lh7a27vzf-go
  backstage.io/kubernetes-id: lh7a27vzf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lh7a27vzf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml