apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lh7a27vzf-go
  janus-idp.io/tekton: lh7a27vzf-go
  backstage.io/kubernetes-id: lh7a27vzf-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lh7a27vzf-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
