apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lh7a27vzf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lh7a27vzf-go 
  name: lh7a27vzf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lh7a27vzf-go 
